charts/kubescape-cloud-operator/README.md, charts/kubescape-prometheus-integrator/README.md
* feat: reduce requests for ephemeral storage
* Update chart version
* Change cloudapi-configmap.yanl extension for fix the typo
Fix the following lint error
```
[ERROR] templates/cloudapi-configmap.yanl: file extension '.yanl' not
valid. Valid extensions are .yaml, .yml, .tpl, or .txt
```
* Update kubescape image tag
* Added prometheus chart (#11)
* Adding kubescape-prometheus
* removed unused volume
* fixed readme table
* update chart version
* update docs link
* update chart release
* update readme
* [cloud-operator] fix upgrade command in readme
* [cloud-operator] add instructions to remove depracated version
Co-authored-by: Vlad Klokun <vklokun@protonmail.ch>
Co-authored-by: David Wertenteil <dwertent@armosec.io>
Co-authored-by: mgi166 <hiromu.mogi@gmail.com>
**Please open the PR …
=> Minor fixes to cloud operator readme (#12)

charts/kubescape-cloud-operator/values.yaml
This PR bumps the Kubevuln version to 0.0.45. This version contains a fix for the ephemeral storage usage.
=> chore: bump Kubevuln version to 0.0.45

charts/kubescape-prometheus-integrator/README.md, charts/kubescape-prometheus-integrator/templates/ks-servicemonitor.yaml, charts/kubescape-prometheus-integrator/values.yaml
I feel that using Prometheus integration makes modifying some Service Monitor properties more convenient.
Specifically, I'd like to make changes so that the interval and scrapeTimeout can be set:
1. Change `interval` to allow scans to be performed at any desired timing.
1. Modify the `scrapeTimeout` value to ensure that scans do not fail even if they exceed `100s` by executing scans with the minimum CPU limit."
=> add interval and scrapeTimeout to values.yaml

charts/kubescape-prometheus-integrator/README.md, charts/kubescape-prometheus-integrator/templates/kubescape/kubescape-deployment.yaml, charts/kubescape-prometheus-integrator/values.yaml
Allow to include and exclude namespaces.
```sh
helm template -n kubescape  kubescape-prometheus-integrator ./charts/kubescape-prometheus-integrator --set "includeNamespaces[0]=ns1" --set "includeNamespaces[1]=ns2" --set "excludeNamespaces[0]=ns3"  --set "excludeNamespaces[1]=ns4" 
```
=> Allow to include and exclude namespaces.

charts/kubescape-prometheus-integrator/README.md, charts/kubescape-prometheus-integrator/templates/kubescape/kubescape-deployment.yaml, charts/kubescape-prometheus-integrator/values.yaml
[Creating this new PR as weill delete the old one: https://github.com/kubescape/helm-charts/pull/57 raised for the same]
As of now, current documentation only shows how to integrate kubescape with prometheus operator aka kube-prometheus-stack. Sometimes people do not use operator but the actual prometheus community helm chart and customise it as per their need. So allow monitoring of kubescape with such custom/non-operator/community helm chart, we need to make use of  [scraping-pod-metrics-via-annotations](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus#scraping-pod-metrics-via-annotations) method. So have amended the kubescape helm chart to allow setting up prometheus pod annotation. 
To test the same, once can clone the  PR -branch locally and go to path: …
=> added way to integrate with non-operator prometheus helm chart

charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml
This fix removes the hostNetwork and hostPort parameters from the host-scanner deployment, since we don't need them anymore.
=> fix(host-scanner): remove hostNetwork and hostPort parameters

charts/kubescape-cloud-operator/templates/kubescape-storage/_helpersKubescapeStorage.tpl, charts/kubescape-cloud-operator/templates/kubescape-storage/apiservice.yaml, charts/kubescape-cloud-operator/templates/kubescape-storage/auth-delegator.yaml, charts/kubescape-cloud-operator/templates/kubescape-storage/auth-reader.yaml, charts/kubescape-cloud-operator/templates/kubescape-storage/backingStorage-deployment.yaml, charts/kubescape-cloud-operator/templates/kubescape-storage/backingStorage-service.yaml, charts/kubescape-cloud-operator/templates/kubescape-storage/k8sApiserver-deployment.yaml, charts/kubescape-cloud-operator/templates/kubescape-storage/k8sApiservice-service.yaml, charts/kubescape-cloud-operator/templates/kubescape-storage/rbac-bind.yaml, charts/kubescape-cloud-operator/templates/kubescape-storage/rbac.yaml, charts/kubescape-cloud-operator/templates/kubescape-storage/sa.yaml, charts/kubescape-cloud-operator/templates/kubescape-storage/tests/test-connection.yaml, charts/kubescape-cloud-operator/values.yaml
This commit adds the Kubscape Storage service into the Helm chart.
Since this is an upcoming feature, it is disabled by default.
Fetch the new chart definition and run the following command:
```
helm -n kubescape install {FETCHED_CHART_PATH}/kubescape-cloud-operator/ --create-namespace --set kubescape.submit=false --set clusterName="ks-aa-test"
```
=> feat: add support for the Kubescape Storage

charts/kubescape-cloud-operator/README.md, charts/kubescape-cloud-operator/assets/otel-collector-config.yaml, charts/kubescape-cloud-operator/values.yaml
Provide the ability to collect CPU and memory utilization metrics by the OpenTelemetry collector.
By default this option is disabled.
=> Added (optional) hostmetrics receiver to otel collector config

charts/kubescape-cloud-operator/values.yaml
Bump the Kubescape Storage AA version to increase etcd message limits even further
=> chore: bump Kubescape Storage AA version

labs/kubescape-relevancy/Chart.yaml, labs/kubescape-relevancy/values.yaml
This PR bumps the Aggregated APIServer version to support the Strategic Merge Patch. Enables changes delivered by kubescape/storage#12.
=> chore(apiserver): bump version to support Strategic Merge Patch

charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml, charts/kubescape-cloud-operator/values.yaml, charts/kubescape-prometheus-integrator/templates/kubescape/kubescape-deployment.yaml, charts/kubescape-prometheus-integrator/values.yaml, labs/kubescape-relevancy/README.md, labs/kubescape-relevancy/templates/kubescape/deployment.yaml, labs/kubescape-relevancy/values.yaml
As part of this PR, added a new env var to Kubescape which was introduced in https://github.com/kubescape/kubescape/pull/1230. It allows setting the concurrency level in which OPA rules are processed. 
By default, Kubescape will not evaluate the OPA rules concurrently (value=1) as it can be a resource-intensive operation that can lead to OOM situations when scanning large clusters. 
N/A 
* https://github.com/kubescape/kubescape/pull/1230
=> Control Kubescape rule processing concurrency by env var

charts/kubescape-cloud-operator/values.yaml, charts/kubescape-prometheus-integrator/values.yaml
- Bump KS version to v2.3.3
- Revert resource limits of gateway & kollector (https://github.com/kubescape/helm-charts/pull/140)
=> Update Kubescape version, revert gateway & kollector limits

charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml, charts/kubescape-cloud-operator/templates/kollector/statefulset.yaml, charts/kubescape-cloud-operator/templates/kubescape-scheduler/cronjob.yaml, charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml, charts/kubescape-cloud-operator/templates/kubevuln-scheduler/cronjob.yaml, charts/kubescape-cloud-operator/templates/kubevuln/deployment.yaml, charts/kubescape-cloud-operator/templates/operator/deployment.yaml
Using read-only containers and only allow certain directories to be writable is a common security hardening practice in the container ecosystem.
This PR is blocked by the linked issues/PRs here:
fix bug where failed reports are written directly to `$HOME`
Open issue(s):
- kubescape caveats:
- decide whether kubescape should ship `/home/ks/.kubescape/*.json`. These files are also downloaded during runtime. In the current setup these files are overwritten at runtime
=> feat: Use read-only filesystem in all components

charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml
In this PR we are moving the previous dedicated **host-scanner**'s namespace (`kubescape-host-scanner`), to the current in use for **kubescape** operator (`kubescape`).
This is useful to avoid communication issues between namespaces when a policy engine is installed on the cluster.
Build kubescape by your own from this branch and run it against a cluster with the following command: `./kubescape scan --enable-host-scan`.
Check if host-scanner is deployed in kubescape namespace.
This is related to this other PR in **kubescape**:
https://github.com/kubescape/kubescape/pull/1217
=> fix: move host-scanner namespace

charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml
`/kubeletcommandline` has been replaced by `/kubeletinfo` endpoint.
Related issue:
* https://github.com/kubescape/host-scanner/pull/46
put an [x] in the box to get it checked
=> fix: update host-scaner container image

labs/kubescape-relevancy/Chart.yaml, labs/kubescape-relevancy/templates/kubescape/configmap.yaml, labs/kubescape-relevancy/values.yaml
Applied the following changes from `master` branch to the `relevancy` branch:
- https://github.com/kubescape/helm-charts/pull/181
- https://github.com/kubescape/helm-charts/pull/172
=> Added urls to Kubescape config and increased memory limits of Kubescape

charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml, charts/kubescape-prometheus-integrator/assets/host-scanner-definition.yaml
this version of the host-scanner removes readiness and liveness endpoints from telemetry to decrease the number of events sent to our backend
=> bump host-scanner version

charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml, charts/kubescape-cloud-operator/templates/operator/deployment.yaml, charts/kubescape-cloud-operator/values.yaml
Adding to operator env var TRIGGER_SECURITY_FRAMEWORK.
If true (default), the operator will trigger scan for "security" fw on top of any framework scan.
=> "Security" fw scan support

charts/kubescape-cloud-operator/templates/operator/clusterrole.yaml
The Operator failed  to retrieve the credentials for images in private repos:
```
{"level":"error","ts":"2023-07-26T21:21:31Z","msg":"unable to get secret","secret name":"reg-cred","error":"secrets \"reg-cred\" is forbidden: User \"system:serviceaccount:kubescape:operator\" cannot get resource \"secrets\" in API group \"\" in the namespace \"event-4\""}
```
=> Addin secrets to operator cluster role

charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml
Add tolerations to kubescape deployment
Current helm template for kubescape deployment does not provide a way to add tolerations
Install chart locally and test if tolerations field have been applied to kubescape deployment
Resolved https://github.com/kubescape/helm-charts/issues/58
- [ x] My code follows the style guidelines of this project
- [ x] I have commented on my code, particularly in hard-to-understand areas
- [ x] I have performed a self-review of my code
- [ x] If it is a core feature, I have added thorough tests.
- [ x] New and existing unit tests pass locally with my changes
=> Add tolerations to kubescape deployment template

charts/kubescape-cloud-operator/assets/kubescape-cronjob-full.yaml, charts/kubescape-cloud-operator/assets/kubevuln-cronjob-full.yaml, charts/kubescape-cloud-operator/assets/registry-scan-cronjob-full.yaml, charts/kubescape-cloud-operator/templates/kubescape-scheduler/cronjob.yaml, charts/kubescape-cloud-operator/templates/kubevuln-scheduler/cronjob.yaml
Since `batchv/v1/CronJob` were GA in K8s in version `>= 1.21` any versions prior to that throw an error while trying to install the charts as we use `CronJob` as well. A more clearer error is being thrown now if the resource is not supported.
Helm installations provide a lot of templating functionalities internally such as checking if a given resources definition exists in the cluster already or not, combining this with the ability to conditionally fail the install helps in this case.
Try to install the chart on a K8s version which doesn't support `batch/v1/CronJob` i.e. `< 1.21`
Resolved #112
=> fix: check supported version

charts/kubescape-cloud-operator/assets/kubescape-cronjob-full.yaml, charts/kubescape-cloud-operator/assets/kubevuln-cronjob-full.yaml, charts/kubescape-cloud-operator/assets/registry-scan-cronjob-full.yaml, charts/kubescape-cloud-operator/templates/configs/ks-recurring-cronjob-configmap.yaml, charts/kubescape-cloud-operator/templates/configs/kv-recurring-cronjob-configmap.yaml, charts/kubescape-cloud-operator/templates/configs/registry-scan-recurring-cronjob-configmap.yaml
Bug fix
___
This PR addresses an issue with version checks for CronJobs in the kubescape-cloud-operator. The version checks have been moved from the CronJob files to the ConfigMap files to ensure proper functionality.
___
-`kubescape-cronjob-full.yaml`: Removed the version check for CronJob.
-`kubevuln-cronjob-full.yaml`: Removed the version check for CronJob.
-`registry-scan-cronjob-full.yaml`: Removed the version check for CronJob.
-`ks-recurring-cronjob-configmap.yaml`: Added the version check for CronJob.
-`kv-recurring-cronjob-configmap.yaml`: Added the version check for CronJob.
-`registry-scan-recurring-cronjob-configmap.yaml`: Added the version check for CronJob.
=> Fixing Version Checks for CronJobs

charts/kubescape-cloud-operator/README.md, charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml, charts/kubescape-cloud-operator/assets/kubescape-cronjob-full.yaml, charts/kubescape-cloud-operator/assets/kubevuln-cronjob-full.yaml, charts/kubescape-cloud-operator/assets/registry-scan-cronjob-full.yaml, charts/kubescape-cloud-operator/templates/grype-offline-db/deployment.yaml, charts/kubescape-cloud-operator/templates/kubescape-scheduler/cronjob.yaml, charts/kubescape-cloud-operator/templates/kubevuln-scheduler/cronjob.yaml, charts/kubescape-cloud-operator/templates/node-agent/configmap.yaml, charts/kubescape-cloud-operator/templates/node-agent/daemonset.yaml, charts/kubescape-cloud-operator/values.yaml, charts/kubescape-prometheus-integrator/README.md, charts/kubescape-prometheus-integrator/assets/host-scanner-definition.yaml, charts/kubescape-prometheus-integrator/values.yaml
Enhancement
___
This PR introduces tolerations to the Kubescape Cloud Operator. Tolerations are applied to Kubernetes pods as a way to ensure that they are not scheduled onto inappropriate nodes. The changes also include renaming 'kubescapeHostScanner' to 'hostScanner' and updating the corresponding volumes and volumeMounts. Additionally, the PR introduces changes to the nodeSelector and affinity settings for various components.
___
-`charts/kubescape-cloud-operator/README.md`: Updated the documentation to reflect the renaming of 'kubescapeHostScanner' to 'hostScanner'.
-`charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml`: Updated the host scanner definition to include tolerations, nodeSelector, and affinity settings. …
=> Adding Tolerations to Kubescape Cloud Operator

charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/values.yaml
Bug fix
___
This PR updates the version of the Kubescape Cloud Operator to include a hotfix. The chart version and the app version have been incremented from 1.14.3 to 1.14.4. Additionally, the tag of the Kubescape image in the values.yaml file has been updated to v2.3.8-hotfix.
___
- `charts/kubescape-cloud-operator/Chart.yaml`: The chart version and the app version have been updated from 1.14.3 to 1.14.4.
- `charts/kubescape-cloud-operator/values.yaml`: The tag of the Kubescape image has been updated to v2.3.8-hotfix.
=> Kubescape 2.3.8 Hotfix

.github/workflows/02-e2e-test.yaml
Enhancement
___
This PR introduces an enhancement to the E2E workflow by adding an optional input to override the default system-tests branch. This allows for greater flexibility and control over the testing process.
___
`.github/workflows/02-e2e-test.yaml`: Added a new optional input 'TESTS_BRANCH' to the workflow inputs with a default value of 'master'. This input is then used as a reference when checking out the system-tests repository.
___
Added an optional input to the E2E workflow to override the default system-tests branch
=> Support system tests branch as input

.github/workflows/02-e2e-test.yaml
Overriding the following:
https://github.com/armosec/system-tests/blob/675cc383c77635354e9456d2fbc2cc61759a0fa1/tests_scripts/kubescape/base_kubescape.py#L79
Default value is `release`:
https://github.com/armosec/system-tests/blob/675cc383c77635354e9456d2fbc2cc61759a0fa1/tests_scripts/kubescape/base_kubescape.py#L20C1-L20C15
Enhancement
___
This PR introduces the ability to override the Kubescape branch in the end-to-end testing workflow. This is achieved by adding a new input parameter 'KS_BRANCH' to the GitHub Actions workflow. The default value for this parameter is 'release', but it can be overridden as needed.
___
`.github/workflows/02-e2e-test.yaml`: Added a new input parameter 'KS_BRANCH' to the workflow, with a default value of 'release'. This parameter is then passed to the test …
=> support overriding KS branch in E2E workflow

charts/kubescape-cloud-operator/templates/servicediscovery/job.yaml
Bug fix
___
This pull request addresses an issue with duplicate labels in the service discovery job template of the kubescape-cloud-operator chart. The duplicate labels have been removed to ensure the correct functioning of the service discovery job.
___
`charts/kubescape-cloud-operator/templates/servicediscovery/job.yaml`: The duplicate labels in the metadata section of the service discovery job template have been removed. The labels `app.kubernetes.io/instance` and `helm.sh/chart` were previously declared twice. The second declaration of these labels has been removed.
___
=> fix duplicate labels

charts/kubescape-cloud-operator/templates/node-agent/daemonset.yaml, charts/kubescape-cloud-operator/templates/otel-collector/deployment.yaml, charts/kubescape-cloud-operator/values.yaml
Reverts kubescape/helm-charts#263
[This did not work on GKE](https://github.com/kubescape/helm-charts/pull/263#issuecomment-1691753402).
=> Revert "Profiler suggestions"

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml
Bug fix
___
This PR fixes the configuration of the `relevantImageVulnerabilitiesEnabled` parameter to be based on the relevancy capability rather than the kubevuln component. It also includes a version bump for the application.
___
`charts/kubescape-operator/Chart.yaml`: The application version and chart version have been incremented from 1.15.1 to 1.15.2.
`charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml`: The `relevantImageVulnerabilitiesEnabled` parameter is now set based on the value of `.Values.capabilities.relevancy` instead of `$components.kubevuln.enabled`.
___
The value of `relevantImageVulnerabilitiesEnabled` should be based on the relevancy capability, instead of kubevuln.
=> fix relevancy config

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/templates/_helpers.tpl, charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/values.yaml
Refactoring
___
This PR removes the cloud_provider logic from the helm chart of the kubescape-operator. It also includes a version bump for the helm chart from 1.15.2 to 1.15.3. 
The clusterServer value has been removed
___
`charts/kubescape-operator/templates/_helpers.tpl`: The cloud_provider logic has been removed from this file.
`charts/kubescape-operator/Chart.yaml`: The version and appVersion have been updated from 1.15.2 to 1.15.3.
`charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml`: The reference to cloud_provider has been removed from the clusterProvider field.
`charts/kubescape-operator/templates/kubescape/deployment.yaml`: The cloud_provider logic has been removed and replaced with specific cloud provider metadata fields.
=> remove cloud_provider

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Bug fix
___
This PR updates the Kubescape Operator chart and deployment configuration. It fixes the 'runAsUser' issue in the Kubescape deployment, enabling the security context and setting the 'runAsUser' and 'fsGroup' to 65532. It also sets the container to run as non-root and makes the root filesystem read-only. Additionally, the PR updates the version of the application in the chart and README from 1.15.3 to 1.15.4.
___
`charts/kubescape-operator/Chart.yaml`: The application version and chart version have been updated from 1.15.3 to 1.15.4.
`charts/kubescape-operator/README.md`: The application version and chart version in the README badges have been updated from 1.15.3 to 1.15.4.
`charts/kubescape-operator/templates/kubescape/deployment.yaml`: The security context has been enabled …
=> fix runAsUser for kubescape deployment

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Enhancement
___
This PR updates the version of the Kubescape Operator chart from 1.15.4 to 1.15.5. The changes are reflected in the Chart.yaml and README.md files.
___
`charts/kubescape-operator/Chart.yaml`: Updated the 'version' and 'appVersion' from 1.15.4 to 1.15.5.
`charts/kubescape-operator/README.md`: Updated the version badge from 1.15.4 to 1.15.5.
=> release: bump chart version

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Enhancement
___
This PR updates the Kubescape Operator chart and images. It includes version bumps for the chart, app, and various images used within the chart. The changes aim to keep the application up-to-date with the latest versions.
___
`charts/kubescape-operator/Chart.yaml`: The chart and app versions have been updated from 1.15.6 to 1.16.0.
`charts/kubescape-operator/README.md`: The version badges in the README have been updated to reflect the new version, 1.16.0.
`charts/kubescape-operator/values.yaml`: The image tags for kubescape, operator, kubevuln, otelCollector, storage, nodeAgent, and serviceDiscovery have been updated to their respective newer versions.
</details>
=> bump images

charts/kubescape-operator/templates/_helpers.tpl, charts/kubescape-operator/templates/node-agent/clusterrole.yaml, charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Enhancement
___
This PR enhances the Role-Based Access Control (RBAC) for application profile CRDs by adding new resources to the cluster role. It also introduces a new configuration for enabling the application profile service. Additionally, the PR updates the image repositories and tags for the storage and node-agent services to use a different source.
___
`charts/kubescape-operator/templates/_helpers.tpl`: Added a new helper for runtime observability configuration.
`charts/kubescape-cloud-operator/README.md`: Removed the content of the README file, indicating the deprecation of the Kubescape Operator.
`charts/kubescape-operator/templates/node-agent/clusterrole.yaml`: Added new resources ("applicationactivities", "applicationprofiles", "applicationprofilesummaries") to the cluster role …
=> add rbac for application profile CRDs

charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml, charts/kubescape-operator/templates/kubescape/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Enhancement
___
This PR enhances the labeling of ConfigMaps in the Kubescape Operator. It introduces a new label `kubescape.io/infra` to the `cloudapi-configmap.yaml` and `kubescape/configmap.yaml` files. This label helps in better identification and management of ConfigMaps.
___
`charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml`: Added a new label `kubescape.io/infra: config` to the metadata of the ConfigMap.
`charts/kubescape-operator/templates/kubescape/configmap.yaml`: Added a new label `kubescape.io/infra: kubescape-config` to the metadata of the ConfigMap.
</details>
___
=> added label to configmaps

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/autoupdater/cronjob.yaml, charts/kubescape-operator/templates/autoupdater/rbac.yaml, charts/kubescape-operator/templates/autoupdater/serviceaccount.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
This PR adds the automatic upgrading capability. It’s an experimental feature that checks for the Kubescape Helm chart updates in the background and upgrades the Kubescape release accordingly.
Since it comes with an elevated security risk, users should make sure to read the associated README changes before they decide to use it.
Run the following command to install the Helm chart with the Helm Release Upgrader enabled:
```
helm upgrade --install kubescape ./charts/kubescape-operator/ -n kubescape --create-namespace \
--set clusterName=`kubectl config current-context` \
--set account=YOUR_ACCOUNT_ID \
--set server=api.armosec.io \
--set capabilities.autoUpgrading="enable"
```
Then take a look at your Kubescape release revsions with:
```
helm -n kubescape list
```
You should see the release …
=> feat: add the automatic upgrading capability

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Refactoring
___
This PR removes the `privileged: true` flag from the node-agent pod and adds specific capabilities to the security context of the pod. It also adds an annotation to allow the node-agent to run on kernels with AppArmor. The changes are based on similar modifications in the Inspektor Gadget project and have been tested on Ubuntu (minikube) and GCP with Linux 5.15.
___
`charts/kubescape-operator/templates/node-agent/daemonset.yaml`: Removed the `privileged: true` flag from the security context of the node-agent pod and added specific capabilities. Also added an annotation to allow the node-agent to run on kernels with AppArmor.
`charts/kubescape-operator/values.yaml`: No significant changes, just a minor formatting adjustment.
</details> …
=> Removing privileged flag on the node-agent Pod

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/templates/storage/tests/test-connection.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Refactoring
___
This PR aims to improve the reliability of Kubescape's deployment by explicitly specifying 'docker.io' as the image registry in various places where it was previously omitted. This change is necessary due to varying default configurations in different container engines or systems, which could lead to deployment failures. The PR affects the Kubescape helm charts and updates the image repository references in several YAML files.
___
`charts/kubescape-operator/README.md`: Updated the image reference for the debug command to include 'docker.io'.
`charts/kubescape-operator/templates/storage/deployment.yaml`: Updated the image reference for the initContainers to include 'docker.io'.
`charts/kubescape-operator/templates/storage/tests/test-connec …
=> Add docker.io image registry identifier where missing

charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml, charts/kubescape-operator/templates/kubevuln/clusterrole.yaml, charts/kubescape-operator/templates/operator/clusterrole.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Enhancement
___
This PR introduces the experimental feature of Vex generation to the Kubescape Operator Helm chart. It adds a new flag `--set kubevuln.config.vexGeneration=true` to enable this feature. Additionally, it modifies the ClusterRoles for Kubevuln and Operator to provide the necessary access to the objects.
___
`charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml`: Added a new configuration parameter "vexGeneration" to enable or disable the experimental feature of Vex generation.
`charts/kubescape-operator/templates/kubevuln/clusterrole.yaml`: Updated the resources list to include "openvulnerabilityexchangecontainers" to provide necessary access for the Vex generation feature. …
=> Adding Vex support in the helm-chart

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Refactoring
___
This PR includes the following changes:
- Removes the BPF and PERFMON capabilities from the node-agent container as they are not supported by newer kernel versions and are covered by other capabilities.
- Adds SE Linux context to the node-agent container for enhanced security.
___
`charts/kubescape-operator/templates/node-agent/daemonset.yaml`: - Removed BPF and PERFMON from the list of added capabilities for the node-agent container.
- Added SE Linux options with type 'spc_t' to the security context of the node-agent container.
</details>
___
Removing the BPF and PERFMON capabilities from the node-agent container requirements. They are covered by other capabilities already but they are not supported by newer kernel versions.
Beyond this …
=> Removing BPF/PERFMON capabilities (not supported in every kernel)

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/NOTES.txt, charts/kubescape-operator/templates/configs/matchingRules-configmap.yaml, charts/kubescape-operator/templates/operator/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Enhancement
___
This PR introduces the Continuous Scanning feature in Kubescape, a tool for Kubernetes security. The main changes include:
- Enabling Continuous Scanning in the Kubescape Operator Helm chart.
- Providing detailed documentation on how to use the Continuous Scanning feature.
- Adding a new ConfigMap for matching rules related to continuous scanning.
- Modifying the operator deployment to include the new ConfigMap.
- Updating the values.yaml file to include configurations for continuous scanning.
Once kubescape/storage#59 and kubescape/operator#174 are merged, we can use our proper Quay images.
___
`charts/kubescape-operator/README.md`: Added extensive documentation on the Continuous Scanning feature, including its installation, accessing …
=> feat: support the Continuous Scanning capability

charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Enhancement
___
This PR allows the busybox image used in the Kubescape Operator to be configurable via the values file. The main changes include:
- Addition of `initImage` field in the values file for the busybox image configuration.
- Modification of the `deployment.yaml` to use the busybox image configuration from the values file.
___
`charts/kubescape-operator/templates/storage/deployment.yaml`: The busybox image and its pull policy used in the init container are now fetched from the values file instead of being hardcoded.
`charts/kubescape-operator/values.yaml`: Added a new `initImage` field under `storage` for configuring the busybox image repository, tag, and pull policy.
</details>
___
Resolves [Add value for the Busybox pod registry and …
=> Get busybox image from values file

charts/kubescape-operator/templates/_helpers.tpl, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Refactoring, Enhancement
___
This PR includes two main changes:
- The KS image tag has been updated from v3.0.0 to v3.0.1.
- The capabilities logic in the _helpers.tpl file has been refactored for better clarity and organization. The capabilities have been grouped into categories: configuration scanning, image vulnerabilities scanning, runtime, and others. Some conditions have also been simplified.
___
`charts/kubescape-operator/templates/_helpers.tpl`: The logic for enabling various capabilities has been refactored. The conditions for enabling 'kubescape', 'kubescapeScheduler', 'kubevuln', and 'kubevulnScheduler' have been simplified. The 'nodeScan' capability is no longer a condition for enabling 'kubescape' and 'kubescapeScheduler'. …
=> Bump KS image tag

charts/kubescape-operator/templates/servicediscovery/job.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
- Updated service discovery job to V2
- Bump component versions with support for SD v2
=> Support for service discovery v2

charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Refactoring
___
This PR focuses on the removal of an unnecessary initContainer from the storage deployment in the kubescape-operator chart. The initContainer named 'fix-permissions' was previously used to set permissions on a data volume. However, it seems this operation is no longer required, hence the initContainer has been removed. Additionally, the PR includes minor formatting changes in the values.yaml file.
___
- `charts/kubescape-operator/templates/storage/deployment.yaml`: The 'fix-permissions' initContainer has been removed from the storage deployment. This initContainer was previously used to set permissions on a data volume.
- `charts/kubescape-operator/values.yaml`: Minor formatting changes have been made. No significant changes in the …
=> removing storage initContainer no longer needed

charts/kubescape-operator/templates/_helpers.tpl, charts/kubescape-operator/templates/synchronizer/clusterrole.yaml, charts/kubescape-operator/templates/synchronizer/clusterrolebinding.yaml, charts/kubescape-operator/templates/synchronizer/configmap.yaml, charts/kubescape-operator/templates/synchronizer/deployment.yaml, charts/kubescape-operator/templates/synchronizer/networkpolicy.yaml, charts/kubescape-operator/templates/synchronizer/serviceaccount.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
Enhancement
___
This PR introduces a new Synchronizer client to the Kubescape Operator. The main changes include:
- Addition of a new Synchronizer component in the Helm charts, including its deployment, service account, cluster role, cluster role binding, config map, and network policy.
- The Synchronizer is enabled based on the Helm chart configurations.
- The Synchronizer client has specific permissions to get, list, and watch certain resources in the Kubernetes cluster.
- The Synchronizer client's deployment includes specific environment variables, volume mounts, and volumes for its configuration and operation.
- The values.yaml file has been updated to include configurations for the Synchronizer client.
___
- …
=> add synchronizer client

charts/kubescape-operator/README.md, charts/kubescape-operator/assets/host-scanner-definition.yaml, charts/kubescape-operator/assets/kubescape-cronjob-full.yaml, charts/kubescape-operator/assets/kubevuln-cronjob-full.yaml, charts/kubescape-operator/assets/registry-scan-cronjob-full.yaml, charts/kubescape-operator/templates/gateway/deployment.yaml, charts/kubescape-operator/templates/grype-offline-db/deployment.yaml, charts/kubescape-operator/templates/kollector/statefulset.yaml, charts/kubescape-operator/templates/kubescape-scheduler/cronjob.yaml, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/templates/kubevuln-scheduler/cronjob.yaml, charts/kubescape-operator/templates/kubevuln/deployment.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/templates/operator/deployment.yaml, charts/kubescape-operator/templates/otel-collector/deployment.yaml, charts/kubescape-operator/templates/servicediscovery/job.yaml, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/templates/synchronizer/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
enhancement
___
This PR introduces several enhancements to the kubescape-operator Helm chart:
- Global volumes and volumeMounts have been added to various components, including the node agent, host scanner, and others. This allows for more flexible configuration of volumes across different components.
- Custom scheduling options have been introduced, allowing for the configuration of nodeSelector, affinity, and tolerations at a global level. These settings apply to all workloads managed by the kubescape-operator.
- The individual volume, volumeMount, and scheduling configurations in each component have been removed and replaced with the new global configurations.
- The README and values.yaml files have been updated to reflect these changes.
___
<table><thead><tr><th></th><th>Relevant …
=> Global vars

charts/kubescape-operator/templates/_helpers.tpl, charts/kubescape-operator/templates/prometheus-exporter/clusterrole.yaml, charts/kubescape-operator/templates/prometheus-exporter/clusterrolebinding.yaml, charts/kubescape-operator/templates/prometheus-exporter/deployment.yaml, charts/kubescape-operator/templates/prometheus-exporter/networkpolicy.yaml, charts/kubescape-operator/templates/prometheus-exporter/service.yaml, charts/kubescape-operator/templates/prometheus-exporter/serviceaccount.yaml, charts/kubescape-operator/templates/prometheus-exporter/servicemonitor.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
Enhancement
___
This PR introduces the integration of Prometheus Exporter into the Helm charts of the kubescape-operator. The main changes include:
- Enabling Prometheus Exporter in the Helm charts.
- Adding new YAML configuration files for Prometheus Exporter, including deployment, service, service account, network policy, cluster role, and cluster role binding.
- Updating the values.yaml file to include configurations for Prometheus Exporter.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Adding Prometheus Exporter to Helm Charts

charts/kubescape-operator/README.md
documentation
___
- Added a warning in the `kubescape-operator` chart README to inform users that the Auto Upgrading capability does not update Kubernetes resources if they have been manually changed. This is to prevent unexpected behavior and align with Helm's limitations.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Add Warning to Auto Upgrading Documentation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/kubescape-operator/README.md
<li>Added a warning about the Auto Upgrading capability not updating <br>Kubernetes resources after manual …
=> add warning on upgrading releases with manual changes

charts/kubescape-operator/templates/operator/clusterrole.yaml, charts/kubescape-operator/templates/operator/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
enhancement
___
- Added "services" to the resources list in the cluster role to extend permissions.
- Introduced a new environment variable `HELM_RELEASE` in the deployment to track the Helm release version.
- Updated the operator and kubevuln image tags to v0.2.7 and v0.3.6 respectively, preparing for the next release.
___
<tr>
<td>
<details>
<summary><strong>clusterrole.yaml</strong><dd><code>Extend Cluster Role Resources</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> prepare for next release

.github/workflows/02-e2e-test.yaml, charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/assets/kubescape-cronjob-full.yaml, charts/kubescape-operator/assets/kubevuln-cronjob-full.yaml, charts/kubescape-operator/assets/registry-scan-cronjob-full.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
enhancement
___
- Incremented chart and app version to `1.18.9` in Chart.yaml and README.md.
- Fixed header format for content type in cronjob configurations.
- Updated various image tags in values.yaml to newer versions.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Version update</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Increment Chart and App Version for Kubescape Operator</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/kubescape-operator/Chart.yaml
<li>Incremented chart version from <code>1.18.8</code> to <code>1.18.9</code>.<br> <li> Incremented app version from <code>1.18.8</code> to <code>1.18.9</code>.<br>
</details>
</td>
<td><a …
=> prepare hotfix release

charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
___
enhancement, bug_fix
___
- Introduced a new `prometheusAnnotations` configuration option to enable/disable Prometheus annotations globally, improving flexibility in metrics scraping setup.
- Removed the old `prometheusAnnotation` configuration block and replaced it with a more granular `prometheusExporter` option under `nodeAgent.config`.
- Refactored Prometheus annotations in Kubescape deployment and Node Agent DaemonSet to align with the new configuration approach.
___
<tr>
<td>
<details>
<summary><strong>deployment.yaml</strong><dd><code>Refactor Prometheus Annotations in Kubescape Deployment</code>&nbsp; &nbsp; </dd></summary>
<hr> …
=> fix prometheus config

charts/kubescape-operator/templates/node-agent/clusterrole.yaml, charts/kubescape-operator/templates/synchronizer/clusterrole.yaml, charts/kubescape-operator/templates/synchronizer/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
enhancement
___
- Added support for `networkneighborhoods` resource in ClusterRoles and ConfigMap.
- Updated ClusterRoles to include `networkneighborhoods` in the resources list for enhanced access control.
- Configured synchronization strategy for `networkneighborhoods` to ensure proper handling.
___
<tr>
<td>
<details>
<summary><strong>clusterrole.yaml</strong><dd><code>Add NetworkNeighborhoods Resource to ClusterRole</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/kubescape-operator/templates/node-agent/clusterrole.yaml
<li>Added <code>networkneighborhoods</code> to the resources list for specific …
=> add rbac and config for NetworkNeighborhood objects

charts/kubescape-operator/templates/synchronizer/clusterrole.yaml, charts/kubescape-operator/templates/synchronizer/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
___
enhancement
___
- Added permissions for `storageclasses`, `rolebindings`, and `clusterrolebindings` to the ClusterRole to enhance access control.
- Updated the ConfigMap to include configurations for new resources with patch strategies, improving synchronization capabilities.
___
<tr>
<td>
<details>
<summary><strong>clusterrole.yaml</strong><dd><code>Extend ClusterRole Permissions for Storage and RBAC Resources</code></dd></summary>
<hr>
charts/kubescape-operator/templates/synchronizer/clusterrole.yaml
<li>Added permissions for <code>storageclasses</code> in the <code>storage.k8s.io</code> API group.<br> <li> Added permissions for …
=> Add permissions for storage classes and RBAC resources***

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/_helpers.tpl, charts/kubescape-operator/templates/configs/custom-ca-certificates.yaml, charts/kubescape-operator/templates/gateway/deployment.yaml, charts/kubescape-operator/templates/kollector/statefulset.yaml, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/templates/kubevuln/deployment.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/templates/operator/deployment.yaml, charts/kubescape-operator/templates/synchronizer/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
Add support for custom CA certificates in Kubescape-operator deployment.
```
global.overrideDefaultCaCertificates.enabled | bool | `false` | Use to enable custom CA Certificates
global.overrideDefaultCaCertificates.caCertificates | string | `""` | Set the custom CA Certificates file in all container
```
=> Add support for custom CA certificates in KS containers

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml, charts/kubescape-operator/values.yaml
Enabling the user to use an alternative URL with Kubevuln/Grype
=> Adding the option to override the Grype DB URL

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
We are adding a capability (in conjunction with the node agent feature https://github.com/kubescape/node-agent/pull/282 ) to deploy multiple node agents (as StatefulSets) on the same node for testing purposes
=> Multiplying the node-agent for testing purposes

charts/kubescape-operator/templates/prometheus-exporter/servicemonitor.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Fix the prometheus-exporter service monitor that misses the endpoint configuration
* Resolved #390
=> Fix prometheus-exporter missing endpoints

charts/kubescape-operator/templates/node-agent/clusterrole.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Adding RBAC permissions to create events

charts/kubescape-operator/templates/node-agent/service.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
No Pods was wrapped by the selector. This commit migrates the node-agent Service template to use kubescape-operator.selectorLabels defined in the `_helpers.tpl` file.
Add:
```yaml
....
....
selector:
app.kubernetes.io/component: node-agent
app.kubernetes.io/instance: kubescape
app.kubernetes.io/name: kubescape-operator
....
....
```
To the `node-agent Kubernetes Service`.
If the above selector filter is _not_ on the service one will see:
When added ... you'll see:
---
- [NOT_RELEVANT] My code follows the style guidelines of this project ( changing a Service YAML template here )
- [NOT_RELEVANT] I have commented on my code, particularly in hard-to-understand areas
- [NOT_RELEVANT] If it is a core feature, I have added thorough tests.
- [NOT_RELEVANT] New and existing unit tests pass …
=> The selector on the node-agent svc was not working.

charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
This PR fixes: https://github.com/kubescape/node-agent/issues/412
=> Fixing bug where exporter config was set without synchronizer

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
I still think we should rationalize our mounts, but at least now we look more like inspektor
=> mount hostpath /var to node-agent

charts/kubescape-operator/templates/configs/image-pull-secret.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
This update enhances the handling of `imagePullSecrets` by allowing users to generate an image pull secret dynamically based on provided credentials. Previously, the `imagePullSecrets` value was limited to referencing an existing secret. With this change, users can specify credentials and the chart will generate the required secret.
=> image pull secret generation using provided credentials

charts/kubescape-operator/templates/prometheus-exporter/deployment.yaml, charts/kubescape-operator/values.yaml
When I added volume mounts for the kubevuln component, I also noticed differences for the Prometheus Exporter component in Argo CD. I assume this is a copy-paste error that has not yet been discovered.
=> fixed copy paste mistake for Prometheus Exporter volumes

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
* operator
> [Full Changelog](https://github.com/kubescape/operator/compare/v0.2.55...v0.2.60)
* chore(deps): Bump golang.org/x/crypto from 0.27.0 to 0.31.0 by @dependabot in [operator#274](https://github.com/kubescape/operator/pull/274)
* bump dependencies to fix vulnerabilities by @matthyx in [operator#275](https://github.com/kubescape/operator/pull/275)
* fix registry scanning bug for empty repositories by @refaelm92 in [operator#276](https://github.com/kubescape/operator/pull/276)
* fix: trigger ApplicationProfile scan (relevancy) whenever the ApplicationProfile is ready by @amirmalka in [operator#277](https://github.com/kubescape/operator/pull/277)
* fix: scan only complete ApplicationProfiles by @amirmalka in [operator#278](https://github.com/kubescape/operator/pull/278)
* kubevuln …
=> fix relevancy vulnerability scans, prepare new release

charts/kubescape-operator/values.yaml
Fixed some extra whitespace in the serviceScanConfig.enabled key in the operator chart defaults
=> Fix serviceScanConfig.enabled whitespace

charts/kubescape-operator/assets/host-scanner-definition.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Modified the AppArmor profile configuration to use the `nodeAgent.name` value from the Helm chart values instead of hardcoding `node-agent`. This change allows for more flexible naming of the node agent container.
=> fix: annotation for node-agent should use dynamic name

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
This PR updates the synchronizer to stop retrying connections when invalid credentials are detected. This prevents unnecessary retries and ensures better error handling in cases of authentication failures.
- [kubescape/synchronizer#103](https://github.com/kubescape/synchronizer/pull/103)
=> fix: stop synchronizer from retrying connection on invalid credentials

charts/kubescape-operator/templates/prometheus-exporter/clusterrole.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
I just recognized that I missed updating the ClusteRole for prometheus-exporter in order to access the additional Kubescape CustomResources.
```
{"level":"info","ts":"2025-01-08T18:41:18Z","msg":"prometheus metrics server started","port":8080,"path":"/metrics"}
{"level":"warn","ts":"2025-01-08T18:41:18Z","msg":"failed getting workload configuration scan summaries","error":"workloadconfigurationscansummaries.spdx.softwarecomposition.kubescape.io is forbidden: User \"system:serviceaccount:kubescape:prometheus-exporter\" cannot list resource \"workloadconfigurationscansummaries\" in API group \"spdx.softwarecomposition.kubescape.io\" at the cluster scope"}
{"level":"warn","ts":"2025-01-08T18:41:18Z","msg":"failed getting vulnerability manifest …
```
=> added necessary resources to ClusterRole when workload metrics are enabled

charts/kubescape-operator/templates/storage/_helpersKubescapeStorage.tpl, charts/kubescape-operator/templates/storage/apiservice.yaml, charts/kubescape-operator/templates/storage/ca-secret.yaml, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
This pull request introduces enhancements to the Kubescape operator's storage component, focusing on enabling mutual TLS (mTLS) support. The key changes include generating certificates, updating deployment configurations, and conditionally managing secrets based on the mTLS setting.
Enhancements to mTLS support:
* [`charts/kubescape-operator/templates/storage/_helpersKubescapeStorage.tpl`](diffhunk://#diff-2a9c29dd4f281ac98cef7e20fbaa36f67b63f4313e33990436ffd9d5a6550856R14-R33): Added functions to generate a private key and certificate pair for mTLS (`storage.generateCerts.ca` and `storage.generateCerts.cert`).
* [`charts/kubescape-operator/templates/storage/apiservice.yaml`](diffhunk://#diff-03a926e020af25cc9df8c7036d07bfc7f09bd89a7100b90e44cc5daf82602fe1R10-R24): Updated the API service …
=> Enabling mTLS in storage

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/templates/kubevuln/deployment.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/templates/operator/deployment.yaml, charts/kubescape-operator/templates/synchronizer/deployment.yaml, charts/kubescape-operator/values.yaml
This pull request introduces a new feature to support extra CA certificates in the Helm chart.
* [`charts/kubescape-operator/values.yaml`](diffhunk://#diff-2d5611f69251d498d71f52fa778f6ce1bc93e1e1f46951ede1c50d975bdcad02R204-R206): Added new configuration options under `global.extraCaCertificates` to enable the feature and specify the secret name containing the extra CA certificates.
* [`charts/kubescape-operator/templates/kubescape/deployment.yaml`](diffhunk://#diff-b2d573694275628033f9c8251c96711107d99e5c1a189bdc54fc4bbfc8effd68R206-R209): Updated to mount and use the extra CA certificates if the feature is enabled. [[1]](diffhunk://#diff-b2d573694275628033f9c8251c96711107d99e5c1a189bdc54fc4bbfc8effd68R206-R209) [[2]](diffhunk://#diff-b2d573694275628033f9c8251c96711107d99e5c1a189bdc54fc4 …
=> Add support for mapping extra CA certificates in Kubescape Helm chart

charts/kubescape-operator/templates/_common.tpl, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/templates/kubevuln/deployment.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/templates/operator/admission-webhook.yaml, charts/kubescape-operator/templates/operator/deployment.yaml, charts/kubescape-operator/templates/storage/_helpersKubescapeStorage.tpl, charts/kubescape-operator/templates/synchronizer/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml
This pull request includes changes to the `kubescape-operator` Helm chart templates to improve the handling of extra CA certificates. The main modification involves iterating over the keys in the specified secret and mounting each key as a separate file instead of overriding the whole directory
Changes to improve handling of extra CA certificates:
* [`charts/kubescape-operator/templates/kubescape/deployment.yaml`](diffhunk://#diff-b2d573694275628033f9c8251c96711107d99e5c1a189bdc54fc4bbfc8effd68R212-R216): Added iteration over secret keys to mount each key as a separate file.
* [`charts/kubescape-operator/templates/kubevuln/deployment.yaml`](diffhunk://#diff-f7294729ce6b129a91f13f4ed1b7df6aaab5898ef645730498ad6b331d88d3f9R134-R138): Modified to iterate over secret keys for mounting each …
=> Replace full folder mount to per file mount of extra CA certificates

charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
This pull request includes updates to the `kubescape-operator` to add new configuration options for host sensors and corresponding changes to the test snapshots to reflect these new options.
* Added `hostMalwareSensor` and `hostNetworkSensor` configuration options to `nodeAgent` in `values.yaml`.
* Updated `configmap.yaml` to include the new configuration options for `hostMalwareSensor` and `hostNetworkSensor`.
* Updated test snapshots in `snapshot_test.yaml.snap` to include the new configuration options
=> Enable host sensor configurations

charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/templates/storage/_helpersKubescapeStorage.tpl, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
This pull request includes major changes to the `kubescape-operator` Helm charts to change default configuration options and enable additional security capability. The most important changes include enabling certain features by default, modifying conditions for enabling HTTP visiblity, and enabling mTLS for storage.
Configuration enhancements:
* [`charts/kubescape-operator/templates/node-agent/configmap.yaml`](diffhunk://#diff-b8ccd25dcf7198d49ac143cb1ab55a34bc09894349c91c3d6767ba9ca210094dL24-R24): Modified the condition for enabling `httpDetection` also to consider `runtimeDetection` and `runtimeObservability` settings.
Default capability changes:
* [`charts/kubescape-operator/values.yaml`](diffhunk://#diff-2d5611f69251d498d71f52fa778f6ce1bc93e1e1f46951ede1c50d975bdcad02L86-R86): …
=> Changing default chart settings (node SBOM,mTLS, Admission controller, and HTTP)

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
* Vulnerability scanning capability was broken in recent version, disabling `nodeSbomGeneration` by default until it is fixed
=> disable nodeSbomGeneration

charts/kubescape-operator/assets/host-scanner-definition.yaml, charts/kubescape-operator/templates/_common.tpl, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/templates/kubevuln/deployment.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/templates/operator/deployment.yaml, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/templates/synchronizer/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml
=> disable otel collector when configurations.otelUrl is set

charts/kubescape-operator/templates/operator/networkpolicy.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Operator's network policy was missing an ingress rule for admission controller port.
=> fix operator network policy for admission controller port

ArgoCDApplication.yaml
I've included some new items to the ignoreDifferences array. These resources have random generated data when helm templated causing ArgoCD to generate them at each refresh and marking the Application as not synced.
=> include more resources to ignoreDifferences ArgoCD App

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/templates/storage/service.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
This pull request introduces updates to the `kubescape-operator` Helm chart, focusing on version upgrades, configuration flexibility, and port customization. The most significant changes include updating the chart and application versions, introducing a configurable `serverPort` value, and adjusting templates to use this new value dynamically.
* Updated `version` and `appVersion` in `charts/kubescape-operator/Chart.yaml` from `1.27.3` to `1.27.4` to reflect the new release.
* Added a new `serverPort` value in `charts/kubescape-operator/values.yaml` to allow dynamic configuration of the storage server port. Default is set to `8443`.
* Modified `charts/kubescape-operator/templates/storage/deployment.yaml` to replace hardcoded port `8443` with the new `serverPort` value for `livenessProbe`, …
=> Configurable storage port

charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml, charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
This pull request adds new `includePrefixes` parameters to enhance the configuration of file and directory scanning in the Kubescape operator. These changes expand the scope of monitored paths to improve security and compliance checks.
* **Added `includePrefixes` to `default-rule-binding-namespaced.yaml`:** Expanded the list of monitored paths to include directories like `/etc`, `/var/log/`, `/var/lib/docker/`, and others to improve security rule coverage. (`charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml`, [charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yamlR16](diffhunk://#diff-8a14d00337e0df100dd55de6f73f3656b96a04834bdecd87cae4be14f102f9f4R16))
* **Added `includePrefixes` to `default-rule-binding.yaml`:** Similar …
=> Add includePrefixes to default rule binding and update snapshots

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
This pull request introduces changes to improve the `kubescape-operator's security posture by setting appropriate `readOnly` flags for volume mounts in the `node-agent` configuration. These changes ensure that volumes are marked as read-only wherever possible, reducing the risk of unintended write operations.
* **`daemonset.yaml` Updates**: Added `readOnly: true` to volume mounts for `proxy-secret`, `custom-ca-certificates`, and `extra-ca-certificates` to ensure these sensitive files are mounted as read-only.
* **`values.yaml` Updates**:
- Marked several volume mounts as `readOnly: true`, including `/host`, `/var`, `/lib/modules`, `/sys/fs/cgroup`, `/sys/fs/bpf`, and `/boot`, to restrict write access.
- Retained write access (`readOnly: false`) for specific paths like `/run` (container …
=> Update node-agent volume mounts to specify read-only access where applicable

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
This pull request introduces a feature to support GKE Autopilot allowlists in the `kubescape-operator` Helm chart. The most significant changes include adding configuration options for the allowlist in `values.yaml` and updating the `daemonset.yaml` template to conditionally include the allowlist label.
* **Template update for allowlist label**: Added a conditional block in `charts/kubescape-operator/templates/node-agent/daemonset.yaml` to include the `cloud.google.com/matching-allowlist` label if the allowlist feature is enabled.
* **Configuration options**: Introduced a new `nodeAgent.gke.allowlist` section in `charts/kubescape-operator/values.yaml` with options to enable the allowlist and specify its name.
=> Add GKE Autopilot allowlist configuration to nodeAgent

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/values.yaml
Currently cloudProviderMetadata parameters are forced to passed as plaintext values and some of them are kinda confidential. I would suggest to allow the helm-chart template to accept values from secrets.
Resolved #683
put an [x] in the box to get it checked 
-->
=> WIP:  Use secret to pass provider's metadata

charts/kubescape-operator/templates/_common.tpl, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
This PR updates the `_common.tpl` template logic to decouple `kubescapeScheduler` and `kubevulnScheduler` from the [submit ](https://github.com/kubescape/helm-charts/blob/main/charts/kubescape-operator/templates/_common.tpl#L33). Previously, these pods were only enabled when submit was true, which requires an Armo Cloud account.
With this change:
- `kubescapeScheduler` is enabled based solely on `.Values.capabilities.configurationScan == "enable"`
- `kubevulnScheduler` is enabled based solely on `.Values.capabilities.vulnerabilityScan == "enable"`
This simplifies installation for users running Kubescape in self-managed mode or without an Armo Cloud integration.
=> Remove dependency on `submit` for enabling Kubescape scheduler pods

charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
This pull request introduces changes to enable the `nodeProfileService` feature in the `kubescape-operator` configuration, along with updates to ensure compatibility with the `synchronizer` component. The changes primarily impact configuration files and snapshots related to the operator's capabilities and annotations.
* [`charts/kubescape-operator/templates/node-agent/configmap.yaml`](diffhunk://#diff-b8ccd25dcf7198d49ac143cb1ab55a34bc09894349c91c3d6767ba9ca210094dL31-R31): Modified the logic for enabling `nodeProfileService` to depend on both the `synchronizer` component being enabled and the `nodeProfileService` capability being set to "enable."
* [`charts/kubescape-operator/values.yaml`](diffhunk://#diff-2d5611f69251d498d71f52fa778f6ce1bc93e1e1f46951ede1c50d975bdcad02L108-R108): …
=> enabling node profile capability by default

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
This pull request introduces changes to the `kubescape-operator` Helm chart to enhance the configuration of the node-agent by adding support for the `/var/lib/kubelet` directory mount. These updates include modifications to the `daemonset.yaml` template, the Helm chart values, and associated snapshot tests.
This PR should only be merged and release after this https://github.com/kubescape/node-agent/pull/581 is release in Node-agent.
* **Addition of `KUBELET_ROOT` Environment Variable**:
- Added the `KUBELET_ROOT` environment variable with the value `/var/lib/kubelet` in the `daemonset.yaml` template and reflected this in various snapshot test scenarios (`all capabilities`, `default capabilities`, `disable otel`, `minimal capabilities`, and `relevancy only`). …
=> Add kubelet directory support in node agent configuration

charts/kubescape-operator/templates/kubevuln/deployment.yaml, charts/kubescape-operator/templates/kubevuln/tmp-dir-pvc.yaml, charts/kubescape-operator/values.yaml
This pull request introduces support for persistent storage for the `tmp-dir` volume in the `kubescape-operator` Helm chart, allowing users to optionally enable a PersistentVolumeClaim (PVC) for the temporary directory. The changes include updates to the deployment template, a new PVC template, and configuration options in the `values.yaml` file.
* **Deployment template update**:
- Modified `charts/kubescape-operator/templates/kubevuln/deployment.yaml` to conditionally use a PersistentVolumeClaim for the `tmp-dir` volume if `tmpDirPersistence.enabled` is set to `true`. Otherwise, it defaults to using an `emptyDir`.
* **New PVC template**:
- Added a new template file `charts/kubescape-operator/templates/kubevuln/tmp-dir-pvc.yaml` to define the PersistentVolumeClaim for the `tmp-dir` …
=> tmpDirPersistence configuration for Kubevuln

charts/kubescape-operator/templates/storage/configmap.yaml, charts/kubescape-operator/values.yaml
This pull request introduces changes to the `kubescape-operator` Helm chart to enhance configurability and improve clarity in the configuration options. The key updates include adding a new option to explicitly disable virtual CRDs and ensuring consistency in the configuration files.
* **Support for disabling virtual CRDs explicitly**: Added a new `disableVirtualCRDs` field in `charts/kubescape-operator/values.yaml` to allow users to explicitly enable or disable virtual CRDs, overriding the auto-detection mechanism.
* **Conditional logic for `disableVirtualCRDs` in the ConfigMap**: Updated `charts/kubescape-operator/templates/storage/configmap.yaml` to include conditional logic for setting the `disableVirtualCRDs` field in the configuration JSON based on the value provided in …
=> Implement disableVirtualCRDs configuration in values.yaml

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
This pull request includes a version bump for the `kubescape-operator` Helm chart to align with the updated application version.
* [`charts/kubescape-operator/Chart.yaml`](diffhunk://#diff-a982fcb5ed73d5e096917432336870e77884084d3ceb0ac3914489703a7fb1b7L12-R19): Updated `version` and `appVersion` fields from `1.28.3` to `1.28.4` to reflect the new application release.
=> prepare release 1.28.4
