README.md, charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/values.yaml
* Updated `kubevuln` ephemeral limits
* Update Helm version
=> Updated kubevuln ephemeral limits

.github/workflows/helm-chart-release.yaml, .github/workflows/kubescape.yaml, charts/kubescape-cloud-operator/README.md, charts/kubescape-prometheus-integrator/README.md
=> Updating dev from master

charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-prometheus-integrator/Chart.yaml
Since Helm chart releaser expects both charts to have new versions, bump both included charts.
=> chore: bump both chart versions

.github/workflows/kubescape.yaml, charts/kubescape-cloud-operator/templates/gateway-deployment.yaml, charts/kubescape-cloud-operator/templates/kollector-statefulset.yaml, charts/kubescape-cloud-operator/templates/kubescape-deployment.yaml, charts/kubescape-cloud-operator/templates/kubescape-scheduler-cronjob.yaml, charts/kubescape-cloud-operator/templates/kubevuln-deployment.yaml, charts/kubescape-cloud-operator/templates/kubevuln-scheduler-cronjob.yaml, charts/kubescape-cloud-operator/templates/operator-deployment.yaml, charts/kubescape-prometheus-integrator/templates/kubescape/kubescape-deployment.yaml
Add labels and k8s labels to fix according to controls c-0076, c-0077
=> Per 622 add labels usage and k 8 s labels usage

charts/kubescape-cloud-operator/values.yaml
=> update ks version

.github/workflows/helm-chart-release.yaml, charts/kubescape-cloud-operator/values.yaml, charts/kubescape-prometheus-integrator/values.yaml
Bump KS image tag to `v2.0.178`
=> Bump KS image tag

charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/templates/NOTES.txt
Deal with unsupported charcters in cluster name
=> Deal with unsupported charcters in cluster name

charts/kubescape-cloud-operator/values.yaml
=> fixed env name

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md, charts/kubescape-cloud-operator/templates/ks-ns-role.yaml
* Adding secrets to KS namespace role
* Updating github templates
=> Adding secrets to role

README.md
=> Add CICD docs

charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/README.md, charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml, charts/kubescape-cloud-operator/assets/otel-collector-config.yaml, charts/kubescape-cloud-operator/templates/configs/otel-collector-configmap.yaml, charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml, charts/kubescape-cloud-operator/templates/kubevuln/deployment.yaml, charts/kubescape-cloud-operator/templates/operator/deployment.yaml, charts/kubescape-cloud-operator/templates/otel-collector/deployment.yaml, charts/kubescape-cloud-operator/templates/otel-collector/networkpolicy.yaml, charts/kubescape-cloud-operator/templates/otel-collector/service.yaml, charts/kubescape-cloud-operator/values.yaml, charts/kubescape-prometheus-integrator/Chart.yaml, charts/kubescape-prometheus-integrator/values.yaml
Signed-off-by: Matthias Bertschy <matthias.bertschy@gmail.com>
=> adding otel-collector

.github/workflows/01-update_tag.yaml, README.md, charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/README.md, charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml, charts/kubescape-cloud-operator/assets/otel-collector-config.yaml, charts/kubescape-cloud-operator/templates/configs/otel-collector-configmap.yaml, charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml, charts/kubescape-cloud-operator/templates/kubevuln/deployment.yaml, charts/kubescape-cloud-operator/templates/operator/deployment.yaml, charts/kubescape-cloud-operator/templates/otel-collector/deployment.yaml, charts/kubescape-cloud-operator/templates/otel-collector/networkpolicy.yaml, charts/kubescape-cloud-operator/templates/otel-collector/service.yaml, charts/kubescape-cloud-operator/values.yaml, charts/kubescape-prometheus-integrator/Chart.yaml, charts/kubescape-prometheus-integrator/values.yaml
Signed-off-by: David Wertenteil <dwertent@armosec.io>
I added the OTEL instruction so OTEL can be added inline
=> update otel installation instructions

charts/kubescape-cloud-operator/templates/NOTES.txt
Updating the URL displayed after installing the helm chart from `https://cloud.armosec.io/config-scanning/<cluster name>` to `https://cloud.armosec.io/compliance/<cluster name>`
/cc: @GibliX
=> docs(install): Update URL in after installation

charts/kubescape-cloud-operator/templates/kollector/statefulset.yaml
=> Remove wait time before reporting

charts/kubescape-cloud-operator/templates/gateway/deployment.yaml, charts/kubescape-cloud-operator/templates/kollector/statefulset.yaml, charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml, charts/kubescape-cloud-operator/templates/kubevuln/deployment.yaml, charts/kubescape-cloud-operator/templates/operator/deployment.yaml, charts/kubescape-cloud-operator/values.yaml
* Set default logger level to `warning`
* Set default logger to `zap`
=> feat(logs): set default logger level and name

charts/kubescape-cloud-operator/templates/_cronjob.tpl, charts/kubescape-cloud-operator/templates/kubescape-scheduler/cronjob.yaml, charts/kubescape-cloud-operator/templates/kubevuln-scheduler/cronjob.yaml
Using batch/v1 instead of batch/v1beta1 for api version of CronJob.
Deploy cronjobs.
- Resolved #51
=> chore: Use batch/v1 for CronJob

charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml
=> core(logger): Add logger envs to host scanner template

charts/kubescape-cloud-operator/values.yaml
This will enable us to first test the current state before hiding all the `info` level logs
=> Change default logging level to info

charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml, charts/kubescape-cloud-operator/values.yaml
=> core(values): update KS image tag

charts/kubescape-cloud-operator/templates/gateway/deployment.yaml, charts/kubescape-cloud-operator/templates/kollector/statefulset.yaml
=> adding otel env var

charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml
Adding `KS_HOST_SCAN_YAML` by default.
This will enable us to load the host scanner as defined in the helm-chart
=> Adding KS_HOST_SCAN_YAML env

charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/values.yaml
=> Merge to master - PR number: 94

charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/templates/NOTES.txt, charts/kubescape-cloud-operator/templates/configs/cloudapi-configmap.yaml, charts/kubescape-cloud-operator/templates/kubescape/configmap.yaml, charts/kubescape-cloud-operator/values.yaml
* Clsuter name will be case-sensitive
* Increase Kubescape memory request
* Decrease Kubevln memory request
* Remove the message with the ARMO portal link
=> 1.9.23 fix cluster name

charts/kubescape-cloud-operator/templates/kollector/statefulset.yaml, charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml
Adding hook to Kollector so it will schedule first
=> Adding hooks to kollector

charts/kubescape-cloud-operator/values.yaml, charts/kubescape-prometheus-integrator/values.yaml
=> update ks image tag and requested memory

.github/workflows/03-helm-release.yaml
=> Update "Install Helm" action version

charts/kubescape-prometheus-integrator/Chart.yaml
=> update chart version

charts/kubescape-cloud-operator/templates/kollector/statefulset.yaml
=> revert hooks

charts/kubescape-cloud-operator/assets/host-scanner-definition.yaml, charts/kubescape-cloud-operator/assets/otel-collector-config.yaml, charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml, charts/kubescape-cloud-operator/values.yaml
Added support for sending OpenTelemetry data to KS cloud.
Otel collector will be enabled by default, with ksCloud exporter enabled by default
=> OpenTelemetry - KS cloud support

charts/kubescape-cloud-operator/templates/cluster-role-binding.yaml, charts/kubescape-cloud-operator/templates/cluster-role.yaml, charts/kubescape-cloud-operator/templates/config-map.yaml, charts/kubescape-cloud-operator/templates/daemonset.yaml, charts/kubescape-cloud-operator/templates/service-account.yaml, charts/kubescape-cloud-operator/values.yaml
=> add sniffer to helm chart

charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/README.md, charts/kubescape-cloud-operator/assets/otel-collector-config.yaml, charts/kubescape-cloud-operator/values.yaml
=> Add hostmetrics to relevancy branch

charts/kubescape-cloud-operator/templates/configs/cloudapi-configmap.yaml, charts/kubescape-cloud-operator/templates/node-agent/cluster-role.yaml, charts/kubescape-cloud-operator/templates/node-agent/config-map.yaml, charts/kubescape-cloud-operator/templates/node-agent/daemonset.yaml, charts/kubescape-cloud-operator/templates/node-agent/role-binding.yaml, charts/kubescape-cloud-operator/templates/node-agent/role.yaml, charts/kubescape-cloud-operator/templates/node-agent/service-account.yaml, charts/kubescape-cloud-operator/values.yaml
* Adding labels
* Fix cluster name
* Fix other envs
* Enabling hostmetrics by default
=> Fix node agent

labs/kubescape-relevancy/values.yaml
=> Update falco-driver-loader image to fix my minikube

charts/kubescape-cloud-operator/values.yaml, labs/kubescape-relevancy/values.yaml
=> bump memory requests/limits for schedulers

labs/kubescape-relevancy/templates/kubescape-storage/backingStorage-deployment.yaml, labs/kubescape-relevancy/templates/kubescape-storage/backingStorage-pvc.yaml, labs/kubescape-relevancy/templates/kubevuln/deployment.yaml, labs/kubescape-relevancy/templates/kubevuln/pvc.yaml, labs/kubescape-relevancy/values.yaml
=> add support for persistent storage in relevancy

labs/kubescape-relevancy/values.yaml
=> downgrade kubevuln until we fix the infinite loop

labs/kubescape-relevancy/Chart.yaml, labs/kubescape-relevancy/values.yaml
=> Bump version

labs/kubescape-relevancy/Chart.yaml, labs/kubescape-relevancy/templates/kubevuln/deployment.yaml, labs/kubescape-relevancy/values.yaml
=> bump kubevuln and node-agent, prepare release

labs/kubescape-relevancy/templates/configs/cloudapi-configmap.yaml, labs/kubescape-relevancy/values.yaml
=> adding support for kubevuln scanTimeout in config

labs/kubescape-relevancy/templates/configs/cloudapi-configmap.yaml
=> fix, scanTimeout should be a string

charts/kubescape-cloud-operator/README.md, charts/kubescape-cloud-operator/templates/kubescape/configmap.yaml, charts/kubescape-cloud-operator/values.yaml
- Added URLs section in Kubescape config
=> Added ability to override cloud URLs in Kubescape

.github/workflows/relevancy-e2e-test.yaml, .github/workflows/relevancy-push.yaml, labs/kubescape-relevancy/Chart.yaml, labs/kubescape-relevancy/values.yaml
1. upgrade falco ebpf engine to v4.0.0
2. add relevancy system tests
=> Relevancy update ebpf engine version

labs/kubescape-relevancy/Chart.yaml, labs/kubescape-relevancy/templates/configs/cloudapi-configmap.yaml, labs/kubescape-relevancy/templates/grype-offline-db/deployment.yaml, labs/kubescape-relevancy/templates/grype-offline-db/networkpolicy.yaml, labs/kubescape-relevancy/templates/grype-offline-db/service.yaml, labs/kubescape-relevancy/values.yaml
=> add support for offline grype db

labs/kubescape-relevancy/Chart.yaml, labs/kubescape-relevancy/values.yaml
This PR bumps the Storage API Server to fix namespace deletion when running relevancy.
=> chore: bump APIServer to fix namespace deletion

charts/kubescape-cloud-operator/values.yaml
Increased the default memory limits value from 800MB to 1GB
=> Increase KS memory limits

labs/kubescape-relevancy/templates/configs/cloudapi-configmap.yaml, labs/kubescape-relevancy/values.yaml
Update kollector image and fix quotes for otel
=> update kollector and cfpgmap

labs/kubescape-relevancy/Chart.yaml, labs/kubescape-relevancy/templates/kubescape/configmap.yaml, labs/kubescape-relevancy/values.yaml
Applied the following changes from master branch to the relevancy branch:
- https://github.com/kubescape/helm-charts/pull/181
- https://github.com/kubescape/helm-charts/pull/172
=> Added urls to Kubescape config and increased memory limits of Kubescape

charts/kubescape-cloud-operator/templates/node-agent/daemonset.yaml
=> update node agent proxy

charts/kubescape-cloud-operator/templates/kubescape-storage/k8sApiserver-deployment.yaml
=> add gomemlimit for storage

.github/workflows/00-cicd.yaml, .github/workflows/01-update_tag.yaml, .github/workflows/02-e2e-test.yaml, .github/workflows/03-helm-release.yaml
=> add new workflows

.github/workflows/02-e2e-test.yaml
=> point e2e test to relevancy systest branch + add tests

charts/kubescape-cloud-operator/templates/operator/clusterrole.yaml, charts/kubescape-cloud-operator/templates/operator/role.yaml, charts/kubescape-cloud-operator/values.yaml
Final adjustments before release
=> Adjustments

charts/kubescape-cloud-operator/templates/operator/clusterrole.yaml, charts/kubescape-cloud-operator/templates/operator/role.yaml, charts/kubescape-cloud-operator/values.yaml
* update operator rbacs
* update ks image tag
* wip: Fixed Operator RBACs
---------
=> Adjustments (#202)

charts/kubescape-cloud-operator/templates/kubescape/clusterrole.yaml, charts/kubescape-cloud-operator/templates/node-agent/clusterrole.yaml
=> fix strange RBAC permissions

charts/kubescape-cloud-operator/templates/kubescape/clusterrole.yaml, charts/kubescape-cloud-operator/templates/node-agent/clusterrole.yaml
=> fix strange RBAC permissions (#206)

charts/kubescape-cloud-operator/templates/otel-collector/deployment.yaml
=> set serviceAccountName to default for otel-collector

charts/kubescape-cloud-operator/templates/kubevuln/role.yaml, charts/kubescape-cloud-operator/templates/node-agent/role.yaml, charts/kubescape-cloud-operator/templates/operator/clusterrole.yaml, charts/kubescape-cloud-operator/values.yaml
support summary objects in the storage
=> Summary vuln crd support

charts/kubescape-cloud-operator/values.yaml
=> update ER endpoints: dev and staging

charts/kubescape-cloud-operator/templates/node-agent/configmap.yaml, charts/kubescape-cloud-operator/templates/node-agent/daemonset.yaml, charts/kubescape-cloud-operator/values.yaml
=> rewrite node-agent config

charts/kubescape-cloud-operator/templates/kubevuln/deployment.yaml, charts/kubescape-cloud-operator/templates/storage/deployment.yaml, charts/kubescape-cloud-operator/values.yaml
=> switching deployment strategy to recreate for PV

charts/kubescape-cloud-operator/templates/node-agent/daemonset.yaml, charts/kubescape-cloud-operator/templates/otel-collector/deployment.yaml, charts/kubescape-cloud-operator/templates/storage/deployment.yaml
Adding tolerations and affinity to the components that were missing them
=> core(templates): Adding tolerations

charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/values.yaml
* Update Operator and node-agent images for supporting CRDs
* Update Kollector image with fewer vulnerabilities in it
=> Bump image versions

.github/workflows/02-e2e-test.yaml, charts/kubescape-cloud-operator/templates/node-agent/configmap.yaml
Bug fix
___
This PR addresses issues in the configuration files. It reorders the test matrix in the e2e test workflow and fixes a syntax error in the node-agent configmap.
___
- `.github/workflows/02-e2e-test.yaml`: The test matrix has been reordered. Some tests have been moved to the top of the list, while others have been moved to the bottom. No tests have been added or removed.
- `charts/kubescape-cloud-operator/templates/node-agent/configmap.yaml`: A syntax error in the JSON block has been fixed. The commas at the end of the `InitialDelay` and `updateDataPeriod` lines have been removed.
=> Fix Configuration

charts/kubescape-cloud-operator/values.yaml
=> Update node-agent image tag

.github/workflows/02-e2e-test.yaml, charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml, charts/kubescape-cloud-operator/values.yaml
1. reduce CPU request limit in the kubevuln
2. update image tags in the operator and in the kubevuln
=> Distroless correction

charts/kubescape-cloud-operator/Chart.yaml, charts/kubescape-cloud-operator/README.md, charts/kubescape-cloud-operator/templates/gateway/deployment.yaml, charts/kubescape-cloud-operator/templates/kubescape/deployment.yaml, charts/kubescape-cloud-operator/templates/kubevuln/deployment.yaml, charts/kubescape-cloud-operator/templates/operator/deployment.yaml, charts/kubescape-cloud-operator/templates/storage/deployment.yaml, charts/kubescape-cloud-operator/values.yaml
see reduced number of vulnerabilities:
=> Move to distroless images

charts/kubescape-cloud-operator/values.yaml
=> bump host-scanner to use distroless image

charts/kubescape-cloud-operator/templates/node-agent/daemonset.yaml, charts/kubescape-cloud-operator/templates/otel-collector/deployment.yaml, charts/kubescape-cloud-operator/values.yaml
Using the profiler suggestions I have made some remediations.
=> Profiler suggestions

charts/kubescape-cloud-operator/templates/operator/configmap.yaml, charts/kubescape-cloud-operator/templates/operator/deployment.yaml, charts/kubescape-cloud-operator/values.yaml
using prerelease tag since this PR fixes system tests
=> add config file for operator

charts/kubescape-operator/README.md
Documentation
___
This PR includes several minor adjustments to the README documentation for the Kubescape Operator. The changes mainly involve grammar corrections, rephrasing for clarity, and the removal of a section about removing old versions of the Kubescape helm chart.
___
`charts/kubescape-operator/README.md`: The changes in this file include:
- Removed a section about removing old versions of the Kubescape helm chart.
- Made several grammar corrections and rephrased some sentences for clarity.
- Changed the term "ARMO CloudEndpoint" to "Server CloudEndpoint" in the example configuration.
- Adjusted the description of the Kollector component's functionality.
___
=> Minor changes in the README

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/kubescape/servicemonitor.yaml
=> add labels for servicemonitor

charts/kubescape-operator/templates/servicediscovery/job.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
* Update image versions (after bumping the backend package)
* Adding resources limits and requests to the discovery job
* Resolves #308
* Resolves #305
=> Adding resources to discovery job

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Update serviceDiscovery limits

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/kubescape/deployment.yaml
adding support in AKS cluster based on User Assigned Cluster.
for more information please refer to our documentation. (https://hub.armosec.io/docs/azure-aks)
=> Aks user assigned cluster support

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Bug fix
___
This PR addresses an issue with the CPU limit in the Kubescape Operator values. Previously, the CPU limit was set lower than the requested CPU, which could lead to potential issues. The CPU limit has now been adjusted to match the CPU request, ensuring smoother operation.
___
`charts/kubescape-operator/values.yaml`: The CPU limit under the 'resources' section has been increased from 100m to 150m, matching the CPU request. This change ensures that the CPU limit is not lower than the CPU request.
</details>
___
=> Fixed limits

charts/kubescape-operator/README.md
Documentation
___
This PR updates the installation steps in the README file of the Kubescape Operator. The changes include:
- Replacing the old installation steps with a new, simplified command.
- Adding instructions to verify the installation.
- Providing commands to view scan summaries and detailed reports.
- Adding uninstallation instructions.
- Changing the value of `capabilities.continuousScan` from `enabled` to `enable` in the continuous scanning section.
___
`charts/kubescape-operator/README.md`: The README file of the Kubescape Operator has been updated with new installation steps, verification instructions, commands to view scan results, and uninstallation steps. The value of `capabilities.continuousScan` has also been changed from `enabled` to …
=> Update installation steps

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
enhancement
___
This PR is for the release of version 1.16.4. The changes include:
- Update of the version number in the Chart.yaml file from 1.16.3 to 1.16.4.
- Update of the appVersion in the Chart.yaml file from 1.16.3 to 1.16.4.
- Update of the version and appVersion in the README.md file from 1.16.3 to 1.16.4.
___
- `charts/kubescape-operator/Chart.yaml`: The version and appVersion have been updated from 1.16.3 to 1.16.4.
- `charts/kubescape-operator/README.md`: The version and appVersion badges have been updated from 1.16.3 to 1.16.4.
</details>
___
=> Release 1.16.4

charts/kubescape-operator/values.yaml
Refactoring
___
This PR focuses on the removal of duplicate parameters in the 'charts/kubescape-operator/values.yaml' file. Specifically, the 'prometheusAnnotation' parameter, which was repeated, has been removed to avoid redundancy.
___
- `charts/kubescape-operator/values.yaml`: The duplicate 'prometheusAnnotation' parameter has been removed from the file.
</details>
___
=> Delete duplicate parameters

charts/kubescape-operator/README.md, charts/kubescape-operator/assets/host-scanner-definition.yaml, charts/kubescape-operator/templates/_helpers.tpl, charts/kubescape-operator/templates/configs/cloud-secret.yaml, charts/kubescape-operator/templates/configs/components-configmap.yaml, charts/kubescape-operator/templates/gateway/deployment.yaml, charts/kubescape-operator/templates/kollector/statefulset.yaml, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/templates/kubevuln/deployment.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/templates/operator/deployment.yaml, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/tests/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Enhancement
___
This PR introduces support for pre-created cloud secrets in the Kubescape operator. The changes include:
- Modification of the checksums in the `_helpers.tpl` file to support the new cloud secret.
- Addition of a new configuration for the cloud secret, which includes a condition to check if the cloud secret is pre-created.
- If the cloud secret is not pre-created, the default name "cloud-secret" is used, otherwise, the name from the `.Values.credentials.cloudSecret` is used.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Support pre-created cloud secret

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Enhancement
___
This PR focuses on updating the images and tags related to the Network Policy feature. The changes include:
- Updated images for Network Policy feature
- Updated node agent
- Updated tags
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration …
=> Network policy

.github/workflows/02-e2e-test.yaml
Tests
___
This PR focuses on the addition of tests for numpy operations. The details of the changes are not provided in the PR description or commit message, hence the specific tests added are not clear. However, the commit message indicates that these are numpy tests.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> add np tests

charts/kubescape-operator/templates/_helpers.tpl, charts/kubescape-operator/templates/kubescape/clusterrole.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
bug_fix
___
This PR updates the condition for checking the account id in the Kubescape Operator. Previously, the check was performed if the submit flag was enabled. Now, the check is performed only if both the submit flag is enabled and the createCloudSecret flag is true. This change allows the operator to ignore the account id if the secret already exists.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> wip: Ignore account id if secret exists

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Encountered an issue where runc path wasn't found so Instead of setting env variable I think it's better to be part of the helm chart options.
=> Adding an option to set the runtime path to node agent

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
enhancement
___
This PR includes the following changes:
- Updated the image tag for `kubescape` from `v3.0.2-prerelease` to `v3.0.2`.
- Updated the image tag for `otelCollector` from `0.86.0` to `0.91.0`.
- Updated the image tag for `nodeAgent` from `v0.1.128` to `v0.1.130`.
- Updated the image tag for `synchronizer` from `v0.0.17` to `v0.0.24`.
These changes indicate an upgrade in the respective components.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> bump images

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
enhancement
___
- The `kubevuln` image version has been updated in the `kubescape-operator` chart. This is a minor version bump, indicating possible enhancements or bug fixes in the `kubevuln` tool.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration …
=> bump kubevuln

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> bump synchronizer

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
enhancement
___
This PR includes updates to the image tags for the operator, kubevuln, and node-agent in the values.yaml file. The changes are as follows:
- The operator image tag has been updated from v0.1.69 to v0.1.70.
- The kubevuln image tag has been updated from v0.2.138 to v0.2.139.
- The node-agent image tag has been updated from v0.1.132 to v0.1.133.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Hotfix naming convention

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
enhancement
___
This PR includes several enhancements:
- The chart and app versions have been updated from 1.16.9 to 1.17.0.
- The version information in the README has been updated to reflect the new version 1.17.0.
- Two new environment variables `KS_LOGGER_LEVEL` and `KS_LOGGER_NAME` have been added to the storage deployment configuration.
- Several changes have been made to the values file, including enabling runtime observability and network policy service, updating the storage, node-agent, and synchronizer image tags, and adding logger level and name.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> Version 1.17

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Enhancement
___
- The Docker image tag for the `node-agent` has been updated in the `values.yaml` file. This change indicates a new version of the `node-agent` is being used.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 …
=> bump version to 135

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml
Requires https://github.com/helm-unittest/helm-unittest/pull/220
___
Tests
___
This PR enhances the unit testing of the `kubescape-operator` by adding more test scenarios in the `snapshot_test.yaml` file. The changes include:
- Renaming the test suite from 'Full Snapshot' to 'Snapshot tests'.
- Adding three new test scenarios: 'all capabilities', 'minimal capabilities', and 'default capabilities'. Each scenario has different configurations and assertions.
- The 'all capabilities' test scenario tests the operator with all capabilities enabled.
- The 'minimal capabilities' test scenario tests the operator with minimal settings.
- The 'default capabilities' test scenario tests the operator with a mix of enabled and disabled capabilities.
___
<table><thead><tr><th></th><th>Relevant …
=> Moreunittests

.github/workflows/02-e2e-test.yaml, ArgoCDApplication.yaml, charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Bump versions

.github/workflows/kubescape.yaml, charts/kubescape-operator/values.yaml
___
enhancement
___
- Set a default value for `clusterName` in the Helm chart values to simplify initial configurations.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>values.yaml</strong><dd><code>Set Default Cluster Name in Helm Values</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/kubescape-operator/values.yaml
- Set a default value for `clusterName` to "cluster".
</details>
</td>
<td><a href="https:/kubescape/helm-charts/pull/400/files#diff-2d5611f69251d498d71f52fa778f6ce1bc93e1e1f46951ede1c50d975bdcad02">+1/-1</a>&nbsp; &nbsp; &nbsp; …
=> Set default cluster name

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/configs/private-registries-creds-secret.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
___
enhancement
___
- Added support for `skipTLSVerify` in registry credentials, allowing users to bypass TLS verification.
- Updated snapshot tests to include `skipTlsVerify: true` for testing registry credentials.
- Documented the `skipTlsVerify` option in `values.yaml` to guide users on how to use this new feature.
___
<tr>
<td>
<details>
<summary><strong>private-registries-creds-secret.yaml</strong><dd><code>Add Skip TLS Verify Support in Registry Credentials Secret</code></dd></summary>
<hr>
charts/kubescape-operator/templates/configs/private-registries-creds-secret.yaml
<li>Added support for <code>skipTLSVerify</code> in registry credentials secret …
=> add skip tls verify in registry creds secret

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
enhancement
___
- Bumped chart version and appVersion in `Chart.yaml` from 1.18.5 to 1.18.6.
- Updated the README.md file to reflect the new version in the version badges.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Version update</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Chart.yaml</strong><dd><code>Bump Chart and App Version for Kubescape Operator</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/kubescape-operator/Chart.yaml
<li>Bumped chart version from 1.18.5 to 1.18.6<br> <li> Bumped appVersion from 1.18.5 to 1.18.6<br>
</details>
</td>
<td><a href="https://github.com/kubescape/helm-charts/pull/407/files#diff-a982fcb5ed73d5e096917432336870e77884084d3ceb0ac3914489703a …
=> bump chart version

charts/kubescape-operator/templates/gateway/deployment.yaml, charts/kubescape-operator/templates/grype-offline-db/deployment.yaml, charts/kubescape-operator/templates/kollector/statefulset.yaml, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/templates/kubevuln/deployment.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/templates/operator/deployment.yaml, charts/kubescape-operator/templates/otel-collector/deployment.yaml, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/templates/synchronizer/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
___
enhancement
___
- Added `kubescape.io/tier: "core"` label across various deployments, statefulsets, and daemonsets to ensure consistent labeling and facilitate better resource management and filtering.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
<td>
<details>
<summary><strong>deployment.yaml</strong><dd><code>Add Missing Tier Label to Gateway Deployment</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/kubescape-operator/templates/gateway/deployment.yaml
- Added `kubescape.io/tier: "core"` label to gateway deployment
</details>
</td>
<td><a …
=> added missing tier label

charts/kubescape-operator/README.md
Originally, docs were missing information about chart repo URL and it makes no sense to instruct new users to update chart repo they do not have so it needs to be added as a prior step.
N/A
Run the command in the terminal
N/A
N/A
put an [x] in the box to get it checked 
___
documentation
___
- Added a command to add the Kubescape chart repository (`helm repo add kubescape https://kubescape.github.io/helm-charts/`) in the installation instructions. This ensures users have the repository added before attempting to update or install the Kubescape operator.
- Fixed documentation formatting by ensuring it ends with a newline.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details> …
=> Added chart repo addition command

MAINTAINERS.md, charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
enhancement, documentation
___
- Added Matthias Bertschy as a new maintainer in `MAINTAINERS.md`.
- Bumped Kubescape operator chart and app version to 1.18.7 in `Chart.yaml`.
- Updated `kollector` and `gateway` image tags to new pre-release versions in `values.yaml`.
- Updated version badges in `README.md` to reflect the new version.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>MAINTAINERS.md</strong><dd><code>Update Maintainers List</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> prepare hotfix release for load creds

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/templates/NOTES.txt, charts/kubescape-operator/templates/kubescape-scheduler/cronjob.yaml, charts/kubescape-operator/templates/kubevuln-scheduler/cronjob.yaml, charts/kubescape-operator/templates/kubevuln/clusterrole.yaml, charts/kubescape-operator/templates/node-agent/clusterrole.yaml, charts/kubescape-operator/templates/operator/clusterrole.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
enhancement
___
- Enabled runtime observability in `values.yaml`, enhancing monitoring capabilities.
- Updated component versions for `kubescape`, `kubevuln`, `storage`, `node-agent`, `otelCollector`, `serviceDiscovery`, `kubescapeScheduler`, `kubevulnScheduler`, and `registryScanScheduler` to newer versions for improved functionality and security.
- Incremented chart and app version from 1.18.7 to 1.18.8 in preparation for the new release.
- Updated README and NOTES.txt for better readability and up-to-date information.
- Made configuration changes in ClusterRole definitions to align with the updated capabilities and resources.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Version update</strong></td><td><table>
<tr>
<td>
<details> …
=> prepare smart remediation GA

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/templates/kubescape/clusterrole.yaml, charts/kubescape-operator/templates/kubevuln/clusterrole.yaml, charts/kubescape-operator/templates/operator/clusterrole.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
enhancement
___
- Added `workloadconfigurationscansummaries` to the `kubescape` cluster role for enhanced access control.
- Introduced `vulnerabilitymanifestsummaries` to the `kubevuln` cluster role to improve vulnerability management capabilities.
- Updated the operator cluster role to include `vulnerabilitymanifestsummaries` and `workloadconfigurationscansummaries` for a more comprehensive security oversight.
___
<tr>
<td>
<details>
<summary><strong>clusterrole.yaml</strong><dd><code>Extend RBAC for Kubescape with WorkloadConfigurationScanSummaries</code></dd></summary>
<hr>
charts/kubescape-operator/templates/kubescape/clusterrole.yaml
<li>Added …
=> restore missing rbac for storage CRDs

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
___
enhancement
___
- Updated image tags for `kubevuln`, `storage`, and `nodeAgent` to newer versions, likely incorporating bug fixes, performance improvements, or new features.
- Attempted to fix `nodeAgent` service monitor configuration, but introduced a potential misconfiguration (`disable` instead of `false`).
___
<tr>
<td>
<details>
<summary><strong>values.yaml</strong><dd><code>Update Image Tags and Fix NodeAgent ServiceMonitor Configuration</code></dd></summary>
<hr>
charts/kubescape-operator/values.yaml
<li>Updated <code>kubevuln</code> image tag from <code>v0.3.11</code> to <code>v0.3.13</code>.<br> <li> Updated <code>storage</code> image tag …
=> Fixed SBOM encoding in storage

.github/workflows/04-helm-release-no-tests.yaml
___
enhancement
___
- Added a new GitHub Actions workflow specifically for releasing Helm charts without running E2E tests.
- The workflow is designed to be triggered manually or by other workflows, with specific inputs for chart selection and commit references.
- It includes steps for setting up the environment, configuring Git, installing Helm, and executing the chart release process using the chart-releaser action.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>04-helm-release-no-tests.yaml</strong><dd><code>Add GitHub Actions Workflow for Helm Chart Release Without Tests</code></dd></summary>
<hr>
.github/workflows/04-helm-release-no-tests.yaml …
=> release workflow without tests

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
___
enhancement
___
- This PR updates the kubevuln image tag in the Helm chart to `v0.3.15`.
- The change ensures compatibility with the latest version of kubevuln.
___
<tr>
<td>
<details>
<summary><strong>values.yaml</strong><dd><code>Update kubevuln image tag in Helm chart</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
charts/kubescape-operator/values.yaml
- Updated the `kubevuln` image tag from `v0.3.14` to `v0.3.15`.
</details>
</td>
<td><a href="https://github.com/kubescape/helm-charts/pull/431/files#diff-2d5611f69251d498d71f52fa778f6ce1bc93e1e1f4 …
=> bump kubevuln version

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/configs/priority-class.yaml, charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Adding priorityClassName to node-agent

charts/kubescape-operator/README.md, charts/kubescape-operator/templates/servicediscovery/job.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Adding proxy-secret volume to the discovery job

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Remove probes

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Bump node-agent image

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Bump kubevuln image

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
next episode of the back and forth :)
=> add missing probes

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/templates/servicediscovery/job.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml
=> Add imagePullSecrets to node-agent and servicediscovery

ArgoCDApplication.yaml
=> altered apiVersion and added required parameters in ArgoCDApplication.yaml

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Updating version of the chart to 1.20.4
=> Update release version

charts/kubescape-operator/templates/gateway/deployment.yaml, charts/kubescape-operator/templates/gateway/scc-rolebinding.yaml, charts/kubescape-operator/templates/gateway/serviceaccount.yaml, charts/kubescape-operator/templates/kollector/scc-rolebinding.yaml, charts/kubescape-operator/templates/kubescape/scc-rolebinding.yaml, charts/kubescape-operator/templates/kubevuln/scc-rolebinding.yaml, charts/kubescape-operator/templates/node-agent/scc-rolebinding.yaml, charts/kubescape-operator/templates/operator/scc-rolebinding.yaml, charts/kubescape-operator/templates/otel-collector/deployment.yaml, charts/kubescape-operator/templates/otel-collector/scc-rolebinding.yaml, charts/kubescape-operator/templates/otel-collector/serviceaccount.yaml, charts/kubescape-operator/templates/servicediscovery/rolebinding.yaml, charts/kubescape-operator/templates/storage/scc-rolebinding.yaml, charts/kubescape-operator/templates/synchronizer/scc-rolebinding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
- Node-agent assigned with the privileged SCC.
- All other components assigned with the nonroot SCC, following the principle of least privilege.
=> Assign appropriate SCC RoleBindings for Kubescape components:

charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml, charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Adding new rule

charts/kubescape-operator/assets/host-scanner-definition.yaml, charts/kubescape-operator/templates/kubescape-scheduler/cronjob.yaml, charts/kubescape-operator/templates/kubevuln-scheduler/cronjob.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> adding SCC for schedulers and host-scanner

charts/kubescape-operator/templates/synchronizer/clusterrole.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> add permissions to application profile

charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
=> Added configurable endpoint detection

charts/kubescape-operator/clamav/clamd.conf, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Muting clamav

charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml, charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Added ptrace rule

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Muting clamav logs

charts/kubescape-operator/templates/operator/clusterrole.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> add operatorcommands to operator clusterrole

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> update synchronizer version

charts/kubescape-operator/templates/operator/clusterrole.yaml
=> change operator clusterrole.yaml to support create/update/delete jobs

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Bumping node agent

charts/kubescape-operator/templates/synchronizer/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> * add registry statuses sync path * bump operator and kubevuln version with registry scan changes

charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml, charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Commenting 2 rules and update unittest

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
manual run https://github.com/kubescape/helm-charts/actions/runs/12428212246
=> prepare new release

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Added node-agent mounts

.github/workflows/02-e2e-test.yaml
* Removed old registry scan tests and replaced with new one
*
=> Update E2E tests

.github/workflows/02-e2e-test.yaml
=> Update missing tests values

charts/kubescape-operator/templates/grype-offline-db/cronjob.yaml, charts/kubescape-operator/templates/grype-offline-db/role.yaml, charts/kubescape-operator/templates/grype-offline-db/rolebinding.yaml, charts/kubescape-operator/templates/grype-offline-db/serviceaccount.yaml, charts/kubescape-operator/templates/kubescape/clusterrole.yaml, charts/kubescape-operator/templates/kubescape/deployment.yaml, charts/kubescape-operator/templates/servicediscovery/rolebinding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
=> enable air-gapped scans

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Prepare new release 1.25.0

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/values.yaml
=> Adding init container option to delay the start of the daemonset

charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml, charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Added web attacks rules

charts/kubescape-operator/templates/node-agent/clusterrole.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
* Node agent should be able to read configmaps to support https://github.com/kubescape/node-agent/pull/472
=> added configmaps to node agent RBAC

charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml, charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> Updating rules

charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml, charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> added io uring detection

charts/kubescape-operator/templates/prometheus-exporter/servicemonitor.yaml
=> add missing condition to install exporter's servicemonitor

charts/kubescape-operator/assets/otel-collector-config.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> remove logs from otel exporter config

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> update kubescape image tag - 3.0.31

charts/kubescape-operator/templates/synchronizer/clusterrole.yaml, charts/kubescape-operator/templates/synchronizer/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Sync roles & clusterroles

charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> tor incoming connection

charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
Reverts kubescape/helm-charts#651
=> Revert "tor incoming connection"

.github/workflows/trigger-performance-test.yaml
=> Trigger performance test

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/values.yaml
=> Adding configuration to decide on the scope of malware scanning

charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml, charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Adding new rules

charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml, charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> update node-agent to fix rule policies

charts/kubescape-operator/templates/node-agent/default-rule-binding-namespaced.yaml, charts/kubescape-operator/templates/node-agent/default-rule-binding.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> added rules

charts/kubescape-operator/templates/synchronizer/clusterrole.yaml, charts/kubescape-operator/templates/synchronizer/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> enable sbom syncing by capability

charts/kubescape-operator/templates/operator/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> support registry skip tls

charts/kubescape-operator/templates/_helpers.tpl, charts/kubescape-operator/templates/kubescape/servicemonitor.yaml, charts/kubescape-operator/templates/storage/deployment.yaml, charts/kubescape-operator/templates/storage/pvc.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
- Support all [Kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels)
- Additional labels to all resources
=> Kubernetes recommended labels and additional labels

charts/kubescape-operator/templates/kubescape/servicemonitor.yaml, charts/kubescape-operator/templates/node-agent/servicemonitor.yaml, charts/kubescape-operator/templates/prometheus-exporter/servicemonitor.yaml, charts/kubescape-operator/values.yaml
Can add labels for ServiceMonitor resources
=> Additional labels for ServiceMonitor

charts/kubescape-operator/templates/node-agent/daemonset.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Migrate apparmor from annotations to fields

charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
=> fix http detection flag

charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/templates/synchronizer/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
This pull request enables sending network events when the `networkEventsStreaming` capability is enabled.
Related PR:
* https://github.com/kubescape/node-agent/pull/519
=> network traffic events capturing

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
=> disable network streaming by default

charts/kubescape-operator/templates/configs/cloudapi-configmap.yaml, charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/tests/snapshot_test.yaml, charts/kubescape-operator/values.yaml
Please see kubescape/kubescape#1834
=> feat: allow scanning of embedded SBOMs

charts/kubescape-operator/templates/node-agent/configmap.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
=> added rule cooldown config

charts/kubescape-operator/templates/operator/deployment.yaml, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap
=> Adding env variable for operator

charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
https://github.com/kubescape/operator/pull/317
=> fix docker config json parsing

charts/kubescape-operator/Chart.yaml, charts/kubescape-operator/README.md, charts/kubescape-operator/tests/__snapshot__/snapshot_test.yaml.snap, charts/kubescape-operator/values.yaml
Remove explicit readOnly: false as it is false by default in Kubernetes, to avoid out-of-sync issues in argoCD
=> remove explicit readOnly: false

charts/kubescape-operator/README.md
=> Fixed urls hub.armo --> kubescape.io
